version: "3.8"

services:

  krakend_ce:
    build:
      dockerfile: krakend.Dockerfile
    ports:
      - 8080:8080
    # Overrides default command so things don't shut down after the process ends.
    volumes:
      - ..:/workspace:cached
    command: sleep infinity

  influxdb:
    image: influxdb:2.2-alpine
    environment:
      - "DOCKER_INFLUXDB_INIT_MODE=setup"
      - "DOCKER_INFLUXDB_INIT_USERNAME=admin"
      - "DOCKER_INFLUXDB_INIT_PASSWORD=supersecretpassword"
      - "DOCKER_INFLUXDB_INIT_ORG=krakend"
      - "DOCKER_INFLUXDB_INIT_BUCKET=krakend"
      #- "DOCKER_INFLUXDB_INIT_RETENTION=30d"
      #- "INFLUXD_REPORTING_DISABLED=true"
    ports:
      - "8086:8086"
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "14268:14268"

#  grafana:
#    build:
#      dockerfile: Dockerfile
#      context: ./grafana
#    ports:
#      - "3003:3000"

#  rabbitmq:
#    image: rabbitmq:3-management
#    ports:
#      - "15672:15672"

#  fake_api:
#    image: jaxgeller/lwan
#    volumes:
#      - ./data:/lwan/wwwroot
#    ports:
#      - "8000:8080"

#  web:
#    build:
#      context: ./web
#    ports:
#      - "3000:3000"

#  kraken_designer:
#    image: devopsfaith/krakendesigner:v2.0
#    ports:
#      - 8787:80

#  jwt_revoke:
#    build:
#      context: ./jwt-revoker
#    ports:
#      - "9000:8080"
#    depends_on:
#      - krakend_ce
